apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: stage
  namespace: argocd
spec:
  destinations:
  - namespace: stage
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/chizchig/openshift.git